[build]
  command = "corepack enable && pnpm install --frozen-lockfile=false && pnpm build && rm -rf site && mkdir site && cp -R dist/* site/"
  publish = "site"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
